In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
cancer = load_breast_cancer()

In [4]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
print(cancer['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [6]:
# Creating a dataframe off of this dictionary

df_features = pd.DataFrame(cancer['data'], columns=cancer['feature_names'])
df_features.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [7]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [8]:
cancer['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [9]:
cancer['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [10]:
# This was just analysing the dataset

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X = df_features
y = cancer['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [13]:
from sklearn.svm import SVC

In [14]:
model = SVC()

In [15]:
model.fit(X_train, y_train)

SVC()

In [16]:
predictions = model.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
print(confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

[[ 56  10]
 [  3 102]]


              precision    recall  f1-score   support

           0       0.95      0.85      0.90        66
           1       0.91      0.97      0.94       105

    accuracy                           0.92       171
   macro avg       0.93      0.91      0.92       171
weighted avg       0.93      0.92      0.92       171



In [41]:
# Using GridSearchCV for hyperparameter tuning

In [26]:
from sklearn.model_selection import GridSearchCV

In [33]:
grid = GridSearchCV(SVC(gamma='auto'), {
    'C':[1,10,20],
    'kernel':['rbf','linear']
}, cv=5, return_train_score=False)

In [34]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [35]:
grid.cv_results_

{'mean_fit_time': array([0.01337428, 0.40709567, 0.01037202, 2.26012454, 0.01175785,
        2.91593218]),
 'std_fit_time': array([2.94628016e-03, 1.01798473e-01, 4.88733538e-04, 1.00049386e+00,
        3.94279487e-04, 1.41844671e+00]),
 'mean_score_time': array([0.00498195, 0.00200458, 0.00578451, 0.00199485, 0.0069818 ,
        0.00260081]),
 'std_score_time': array([5.47096615e-06, 1.23199441e-05, 3.98993531e-04, 6.30834169e-04,
        7.59953377e-07, 2.25329562e-03]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [36]:
grid.best_params_

{'C': 20, 'kernel': 'linear'}

In [37]:
grid.best_estimator_

SVC(C=20, gamma='auto', kernel='linear')

In [38]:
df_cv_results = pd.DataFrame(grid.cv_results_)
df_cv_results.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.013374      0.002946         0.004982    5.470966e-06       1   
1       0.407096      0.101798         0.002005    1.231994e-05       1   
2       0.010372      0.000489         0.005785    3.989935e-04      10   
3       2.260125      1.000494         0.001995    6.308342e-04      10   
4       0.011758      0.000394         0.006982    7.599534e-07      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}             0.6375   
1       linear   {'C': 1, 'kernel': 'linear'}             0.9500   
2          rbf     {'C': 10, 'kernel': 'rbf'}             0.6375   
3       linear  {'C': 10, 'kernel': 'linear'}             0.9375   
4          rbf     {'C': 20, 'kernel': 'rbf'}             0.6375   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0             0.6375              0.625           0.632911           0.632911   
1             0.9375              1.000           0.936709           0.987342   
2             0.6375              0.625           0.632911           0.632911   
3             0.9375              1.000           0.949367           0.987342   
4             0.6375              0.625           0.632911           0.632911   

   mean_test_score  std_test_score  rank_test_score  
0         0.633165        0.004569                4  
1         0.962310        0.026342                3  
2         0.633165        0.004569                4  
3         0.962342        0.026252                2  
4         0.633165        0.004569                4

In [39]:
df_cv_results[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.633165
1       1       linear         0.962310
2      10          rbf         0.633165
3      10       linear         0.962342
4      20          rbf         0.633165
5      20       linear         0.964842

In [40]:
grid.best_score_

0.9648417721518987

In [42]:
# Using RandomizedSearchCV for randomly adjusting the hyper parameters

from sklearn.model_selection import RandomizedSearchCV

In [43]:
rSearch = RandomizedSearchCV(SVC(gamma='auto'), {
    'C':[1,10,20],
    'kernel':['rbf', 'linear']}, 
 cv=5, 
 return_train_score=False, 
 n_iter=2)

In [44]:
rSearch.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [45]:
rSearch.cv_results_

{'mean_fit_time': array([0.0147584 , 2.97206883]),
 'std_fit_time': array([0.00380624, 1.33618369]),
 'mean_score_time': array([0.00618243, 0.00239334]),
 'std_score_time': array([0.00097665, 0.00135164]),
 'param_kernel': masked_array(data=['rbf', 'linear'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[10, 20],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 10}, {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([0.6375, 0.95  ]),
 'split1_test_score': array([0.6375, 0.9375]),
 'split2_test_score': array([0.625, 1.   ]),
 'split3_test_score': array([0.63291139, 0.94936709]),
 'split4_test_score': array([0.63291139, 0.98734177]),
 'mean_test_score': array([0.63316456, 0.96484177]),
 'std_test_score': array([0.00456903, 0.02428855]),
 'rank_test_score': array([2, 1])}

In [46]:
df_rs_results = pd.DataFrame(rSearch.cv_results_)
df_rs_results

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.014758      0.003806         0.006182        0.000977          rbf   
1       2.972069      1.336184         0.002393        0.001352       linear   

  param_C                         params  split0_test_score  \
0      10     {'kernel': 'rbf', 'C': 10}             0.6375   
1      20  {'kernel': 'linear', 'C': 20}             0.9500   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0             0.6375              0.625           0.632911           0.632911   
1             0.9375              1.000           0.949367           0.987342   

   mean_test_score  std_test_score  rank_test_score  
0         0.633165        0.004569                2  
1         0.964842        0.024289                1

In [47]:
rSearch.best_estimator_

SVC(C=20, gamma='auto', kernel='linear')

In [48]:
rSearch.best_score_

0.9648417721518987

In [49]:
rSearch.best_params_

{'kernel': 'linear', 'C': 20}

In [50]:
df_rs_results[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0      10          rbf         0.633165
1      20       linear         0.964842

In [51]:
# It can be inferred that randomizedSearchCV is better than GridSearchCV in case of low computation power, as it randomly
# adjusts the parameters and gives the best score

In [52]:
predictions2 = rSearch.predict(X_test)

In [53]:
print(confusion_matrix(y_test, predictions2))
print('\n')
print(classification_report(y_test, predictions2))

[[ 59   7]
 [  2 103]]


              precision    recall  f1-score   support

           0       0.97      0.89      0.93        66
           1       0.94      0.98      0.96       105

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171

